name: Build wheels with cibuildwheel

on:
  push:
    tags:
      - 'v*.*.*'   # triggers on tags like v0.2.6
  workflow_dispatch:  # manual trigger

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install cibuildwheel & Cython
        run: python -m pip install --upgrade pip cibuildwheel Cython

      - name: Build Linux wheels
        run: CIBW_BUILD_VERBOSITY=1 cibuildwheel --output-dir wheelhouse

      - name: Upload Linux wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux
          path: wheelhouse/*.whl

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install cibuildwheel & Cython
        run: python -m pip install --upgrade pip cibuildwheel Cython

      - name: Build macOS wheels
        run: CIBW_BUILD_VERBOSITY=1 cibuildwheel --output-dir wheelhouse

      - name: Upload macOS wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos
          path: wheelhouse/*.whl

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install cibuildwheel & Cython
        run: python -m pip install --upgrade pip cibuildwheel Cython

      - name: Build Windows wheels
        run: CIBW_BUILD_VERBOSITY=1 cibuildwheel --output-dir wheelhouse

      - name: Upload Windows wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-windows
          path: wheelhouse/*.whl

  release:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-linux
          path: wheelhouse

      - name: Download macOS wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-macos
          path: wheelhouse

      - name: Download Windows wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-windows
          path: wheelhouse

      - name: Create GitHub release and upload wheels
        uses: softprops/action-gh-release@v1
        with:
          files: wheelhouse/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
