name: Build wheels with cibuildwheel

on:
  push:
    tags:
      - 'v*.*.*'    # run when you push tags like v0.1.0
  workflow_dispatch:  # optional manual trigger

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cibuildwheel
        run: python -m pip install --upgrade pip cibuildwheel

      - name: Build Linux wheels (manylinux)
        run: |
          cibuildwheel --output-dir wheelhouse

      - name: Upload linux wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux
          path: wheelhouse/*.whl

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cibuildwheel
        run: python -m pip install --upgrade pip cibuildwheel

      - name: Build macOS wheels
        run: |
          cibuildwheel --output-dir wheelhouse

      - name: Upload macos wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos
          path: wheelhouse/*.whl

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cibuildwheel
        run: python -m pip install --upgrade pip cibuildwheel

      - name: Build Windows wheels
        shell: bash
        run: |
          cibuildwheel --output-dir wheelhouse

      - name: Upload windows wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-windows
          path: wheelhouse/*.whl

  release:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download linux wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-linux
          path: wheelhouse

      - name: Download macos wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-macos
          path: wheelhouse

      - name: Download windows wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-windows
          path: wheelhouse

      - name: Create GitHub release and upload wheels
        uses: softprops/action-gh-release@v1
        with:
          files: wheelhouse/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
